/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui.test {
    export class mainUI extends Scene {
		public lianjiefuwuqi:Laya.Sprite;
		public addr:Laya.TextInput;
		public btn_ConnectServer:Laya.Button;
		public log:Laya.TextArea;
		public content:Laya.TextInput;
		public btn_Send:Laya.Button;
		public btn_Login:Laya.Button;
		public btn_Room:Laya.Button;
		public btn_Other:Laya.Button;
		public btn_CloseConnect:Laya.Button;
		public messageType:Laya.TextInput;
		public requestCount:Laya.TextInput;
		public btn_requestn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/main");
        }
    }
}